os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
- flutter packages pub publish --dry-run
deploy:
  provider: script
  script:
  - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: S8khC+APmIcGM2074fZhBG5QcwUBYw585AZuThDkq6WpaJO7+fnQ4RxXELegcOjdcraZVS6xz7N/DLm5KHuoyja51RM+T9a/IXcsYDTwCPog5CQfiUtm0oc4rqELjHHgSNl31VFCEUul12eu76Cavrr4HhBqIYHyeayx3rBYq0eMgDLpQXA00+Bribje80tL4N5U5pOjeX6ogTpS2TyoPxJh1d8gXT06Bv8hpUoXRM6J7k1tDaYenw9kz3fMbZGtMOWFlMLg5zvG/pENO90gko06xpXdifjdxr77+S47a4OuaoZfTwbSTvwwogVFNHn0qulBRkq5DSAtmI/d9OW+ywxJpO8Aw48V/wsQeojzioeWiQJehDM+fObtb19+lMLeN0MMRceJdrsl024wX6+R4zL9LD1cL0+ZO1P3cOPNwyCfOiFkQmqsgqSvdrq0YNYY0oyFvzVG++a5IsLIeG9KS13R4H1f+DED1VAWjqESoFwM6whJ8yQhWL5PDOXp3xLx4kd7K33V7I5VnDTCJcg4gk88O4ipr/gIb85bO2hsdxLC/9VfFYmorfuW7T81c8n2W6ebyVtgArUIcVoX0xOwiILTTWVgVRhFVntgbQCubjBiooSUVFCmYWcwOWycCxpp6LzFGDNRTQwXhc8sjz6qeWVOsB/ZypQJjfYtfKemRj4=